In [1]:
import pandas as pd
data = {'Name ': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)

lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])

df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [2]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [4]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [5]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [6]:
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [8]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [9]:
df[df['Age']>25]

  Name  Age
1  Bob   30

In [10]:
df['Gender']= ['F','M']

In [11]:
# df.drop('Age', axis=1, inplace=True)

In [12]:
df.isnull()

    Name    Age  Gender
0  False  False   False
1  False  False   False

In [13]:
df.dropna()

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [14]:
df.fillna(0)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [15]:
df.groupby('Gender')['Age'].mean()

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [16]:
df1 = pd.DataFrame({
    'key':[1,2,3],
    'Name':['Alice','Bob','Charlie']
})
df2 = pd.DataFrame({
    'key':[1,2,3],
    'Age':[25,30,35]
})

In [17]:
pd.merge(df1, df2, on='key')

   key     Name  Age
0    1    Alice   25
1    2      Bob   30
2    3  Charlie   35

In [18]:
df1.join(df2, rsuffix='_df2')

   key     Name  key_df2  Age
0    1    Alice        1   25
1    2      Bob        2   30
2    3  Charlie        3   35

In [19]:
df = pd.read_csv('data.csv')
df

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [20]:
df.to_csv('output.csv', index=False)

In [21]:
df.sort_values('Age')

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [22]:
df['Age'].apply(lambda x: x + 1)

0    26
1    31
Name: Age, dtype: int64

In [23]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob']
Length: 2, dtype: str

In [24]:
df['Age'].value_counts()

Age
25    1
30    1
Name: count, dtype: int64